"""add market news summaries table

Revision ID: 2340203c3c60
Revises: 283dd16a563c
Create Date: 2025-07-01 20:21:07.770201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2340203c3c60'
down_revision: Union[str, None] = '283dd16a563c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_aaii_sentiment_id', table_name='aaii_sentiment')
    op.drop_index('ix_aaii_sentiment_survey_date', table_name='aaii_sentiment')
    op.drop_table('aaii_sentiment')
    op.add_column('market_sentiment', sa.Column('news_sentiment_score', sa.Float(), nullable=True))
    op.add_column('market_sentiment', sa.Column('news_sentiment_label', sa.String(length=20), nullable=True))
    op.add_column('market_sentiment', sa.Column('news_confidence', sa.Float(), nullable=True))
    op.alter_column('market_sentiment', 'recorded_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               nullable=True)
    op.alter_column('market_sentiment', 'sentiment_label',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('market_sentiment', 'key_drivers',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.Text(),
               existing_nullable=True)
    op.alter_column('market_sentiment', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.DateTime(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_column('market_sentiment', 'aaii_bearish_pct')
    op.drop_column('market_sentiment', 'aaii_bullish_pct')
    op.drop_column('market_sentiment', 'aaii_neutral_pct')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('market_sentiment', sa.Column('aaii_neutral_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('market_sentiment', sa.Column('aaii_bullish_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('market_sentiment', sa.Column('aaii_bearish_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.alter_column('market_sentiment', 'created_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.alter_column('market_sentiment', 'key_drivers',
               existing_type=sa.Text(),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('market_sentiment', 'sentiment_label',
               existing_type=sa.String(length=50),
               type_=sa.VARCHAR(length=20),
               existing_nullable=True)
    op.alter_column('market_sentiment', 'recorded_at',
               existing_type=sa.DateTime(),
               type_=postgresql.TIMESTAMP(timezone=True),
               nullable=False)
    op.drop_column('market_sentiment', 'news_confidence')
    op.drop_column('market_sentiment', 'news_sentiment_label')
    op.drop_column('market_sentiment', 'news_sentiment_score')
    op.create_table('aaii_sentiment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('survey_date', sa.DATE(), autoincrement=False, nullable=True),
    sa.Column('bullish_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('bearish_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('neutral_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('total_responses', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('data_source', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='aaii_sentiment_pkey')
    )
    op.create_index('ix_aaii_sentiment_survey_date', 'aaii_sentiment', ['survey_date'], unique=False)
    op.create_index('ix_aaii_sentiment_id', 'aaii_sentiment', ['id'], unique=False)
    # ### end Alembic commands ###
