"""Add market sentiment table

Revision ID: 3375f0036170
Revises: 
Create Date: 2025-06-30 18:43:51.176788

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3375f0036170'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_sentiment',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('recorded_at', sa.DateTime(), nullable=True),
        sa.Column('sp500_price', sa.Float(), nullable=True),
        sa.Column('sp500_change_pct', sa.Float(), nullable=True),
        sa.Column('dow_price', sa.Float(), nullable=True),
        sa.Column('dow_change_pct', sa.Float(), nullable=True),
        sa.Column('nasdaq_price', sa.Float(), nullable=True),
        sa.Column('nasdaq_change_pct', sa.Float(), nullable=True),
        sa.Column('vix_value', sa.Float(), nullable=True),
        sa.Column('vix_change_pct', sa.Float(), nullable=True),
        sa.Column('put_call_ratio', sa.Float(), nullable=True),
        sa.Column('treasury_10y_yield', sa.Float(), nullable=True),
        sa.Column('dxy_value', sa.Float(), nullable=True),
        sa.Column('dxy_change_pct', sa.Float(), nullable=True),
        sa.Column('new_highs', sa.Integer(), nullable=True),
        sa.Column('new_lows', sa.Integer(), nullable=True),
        sa.Column('advance_decline_ratio', sa.Float(), nullable=True),
        sa.Column('aaii_bullish_pct', sa.Float(), nullable=True),
        sa.Column('aaii_bearish_pct', sa.Float(), nullable=True),
        sa.Column('aaii_neutral_pct', sa.Float(), nullable=True),
        sa.Column('momentum_score', sa.Float(), nullable=True),
        sa.Column('fear_greed_score', sa.Float(), nullable=True),
        sa.Column('breadth_score', sa.Float(), nullable=True),
        sa.Column('overall_sentiment_score', sa.Float(), nullable=True),
        sa.Column('sentiment_label', sa.String(length=50), nullable=True),
        sa.Column('key_drivers', sa.Text(), nullable=True),
        sa.Column('trend_analysis', sa.Text(), nullable=True),
        sa.Column('data_completeness', sa.Float(), nullable=True),
        sa.Column('created_at', sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_sentiment_id'), 'market_sentiment', ['id'], unique=False)
    op.create_index(op.f('ix_market_sentiment_recorded_at'), 'market_sentiment', ['recorded_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_market_sentiment_recorded_at'), table_name='market_sentiment')
    op.drop_index(op.f('ix_market_sentiment_id'), table_name='market_sentiment')
    op.drop_table('market_sentiment')
    # ### end Alembic commands ###
