"""add quarter_label to economic_indicators

Revision ID: 5a2ddcdaeefe
Revises: 8a331f6f1e2b
Create Date: 2025-07-02 16:14:34.133287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5a2ddcdaeefe'
down_revision: Union[str, None] = '8a331f6f1e2b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('economic_indicators', sa.Column('quarter_label', sa.String(length=20), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('economic_indicators', 'quarter_label')
    # ### end Alembic commands ###
