"""add explanation to fundamentals_analysis

Revision ID: 8dea90388793
Revises: 93e97b5d09b0
Create Date: 2025-07-02 10:54:57.496076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8dea90388793'
down_revision: Union[str, None] = '93e97b5d09b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamentals_analysis', sa.Column('explanation', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamentals_analysis', 'explanation')
    # ### end Alembic commands ###
