"""add quarter_label to economic_indicators

Revision ID: 8f34de49a8d9
Revises: 5a2ddcdaeefe
Create Date: 2025-07-02 16:31:01.711446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8f34de49a8d9'
down_revision: Union[str, None] = '5a2ddcdaeefe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
