"""Remove unused economic indicators from database

Revision ID: 93e97b5d09b0
Revises: 8f34de49a8d9
Create Date: 2025-07-02 19:13:50.615951

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '93e97b5d09b0'
down_revision: Union[str, None] = '8f34de49a8d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('economic_indicators', 'quarter_label')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('economic_indicators', sa.Column('quarter_label', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
