"""add_historical_market_data_tables

Revision ID: d411a1f4f95a
Revises: 3375f0036170
Create Date: 2025-06-30 22:14:37.065572

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd411a1f4f95a'
down_revision: Union[str, None] = '3375f0036170'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aaii_sentiment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('survey_date', sa.Date(), nullable=True),
    sa.Column('bullish_pct', sa.Float(), nullable=True),
    sa.Column('bearish_pct', sa.Float(), nullable=True),
    sa.Column('neutral_pct', sa.Float(), nullable=True),
    sa.Column('total_responses', sa.Integer(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aaii_sentiment_id'), 'aaii_sentiment', ['id'], unique=False)
    op.create_index(op.f('ix_aaii_sentiment_survey_date'), 'aaii_sentiment', ['survey_date'], unique=False)
    op.create_table('market_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('indicator_type', sa.String(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('change_pct', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('market_session', sa.String(), nullable=True),
    sa.Column('data_source', sa.String(), nullable=True),
    sa.Column('is_valid', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_indicators_id'), 'market_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_market_indicators_indicator_type'), 'market_indicators', ['indicator_type'], unique=False)
    op.create_index(op.f('ix_market_indicators_timestamp'), 'market_indicators', ['timestamp'], unique=False)
    op.create_table('market_sentiment_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('analysis_date', sa.DateTime(), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('sentiment_label', sa.String(), nullable=True),
    sa.Column('confidence_level', sa.Float(), nullable=True),
    sa.Column('key_factors', sa.JSON(), nullable=True),
    sa.Column('trend_analysis', sa.Text(), nullable=True),
    sa.Column('historical_context', sa.Text(), nullable=True),
    sa.Column('market_outlook', sa.Text(), nullable=True),
    sa.Column('data_period_start', sa.DateTime(), nullable=True),
    sa.Column('data_period_end', sa.DateTime(), nullable=True),
    sa.Column('indicators_analyzed', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_market_sentiment_analysis_analysis_date'), 'market_sentiment_analysis', ['analysis_date'], unique=False)
    op.create_index(op.f('ix_market_sentiment_analysis_id'), 'market_sentiment_analysis', ['id'], unique=False)
    op.drop_index('ix_market_sentiment_id', table_name='market_sentiment')
    op.drop_index('ix_market_sentiment_recorded_at', table_name='market_sentiment')
    op.drop_table('market_sentiment')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('market_sentiment',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('recorded_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('sp500_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sp500_change_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dow_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dow_change_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nasdaq_price', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('nasdaq_change_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vix_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vix_change_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('put_call_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('treasury_10y_yield', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dxy_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('dxy_change_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('new_highs', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('new_lows', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('advance_decline_ratio', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('aaii_bullish_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('aaii_bearish_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('aaii_neutral_pct', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('momentum_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('fear_greed_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('breadth_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('overall_sentiment_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('sentiment_label', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('key_drivers', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True),
    sa.Column('trend_analysis', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('data_completeness', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='market_sentiment_pkey')
    )
    op.create_index('ix_market_sentiment_recorded_at', 'market_sentiment', ['recorded_at'], unique=False)
    op.create_index('ix_market_sentiment_id', 'market_sentiment', ['id'], unique=False)
    op.drop_index(op.f('ix_market_sentiment_analysis_id'), table_name='market_sentiment_analysis')
    op.drop_index(op.f('ix_market_sentiment_analysis_analysis_date'), table_name='market_sentiment_analysis')
    op.drop_table('market_sentiment_analysis')
    op.drop_index(op.f('ix_market_indicators_timestamp'), table_name='market_indicators')
    op.drop_index(op.f('ix_market_indicators_indicator_type'), table_name='market_indicators')
    op.drop_index(op.f('ix_market_indicators_id'), table_name='market_indicators')
    op.drop_table('market_indicators')
    op.drop_index(op.f('ix_aaii_sentiment_survey_date'), table_name='aaii_sentiment')
    op.drop_index(op.f('ix_aaii_sentiment_id'), table_name='aaii_sentiment')
    op.drop_table('aaii_sentiment')
    # ### end Alembic commands ###
